name: EtriaWallet
version: 1.0
main: com.etriacraft.etriawallet.EtriaWallet
commands:
  wallet:
    usage: /<command>
    aliases: [etriawallet, ew]
permissions:
  etriawallet.create
    description: Allows the player to create a wallet for themselves.
    default: op
  etriawallet.balance
    description: Allows the player to check their own balance.
    default: op